<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Fill-in-the-Array Quiz</title>
<style>
    body {
        font-family: Arial, sans-serif;
        padding: 20px;
    }
    table {
        border-collapse: collapse;
        margin-bottom: 20px;
    }
    td, th {
        border: 1px solid #555;
        padding: 8px;
        text-align: center;
    }
    th {
        background-color: #f2f2f2;
    }
    input {
        width: 50px;
        text-align: center;
    }
    #unlock-image {
        display: none;
        margin-top: 20px;
        max-width: 80%;
    }
    button {
        padding: 10px 20px;
        font-size: 16px;
        cursor: pointer;
        margin-top: 10px;
    }
    #image-id-container {
        margin-bottom: 20px;
    }
</style>
</head>
<body>

<h1>Fill in the Array Quiz</h1>
<p>Fill in the table based on the relationships on the sides.</p>

<div id="image-id-container">
    <label for="image-url">Enter the URL or ID of your unlock image:</label>
    <input type="text" id="image-url" placeholder="https://example.com/myimage.png">
</div>

<table id="quiz-table">
    <thead>
        <tr>
            <th></th>
            <th>1</th><th>2</th><th>3</th><th>4</th><th>5</th>
            <th>6</th><th>7</th><th>8</th><th>9</th><th>10</th>
        </tr>
    </thead>
    <tbody>
        <!-- Rows will be generated by JS -->
    </tbody>
</table>

<button onclick="checkAnswers()">Submit Answers</button>

<img id="unlock-image" src="" alt="Unlocked Image">

<script>
    // --- Correct answer array
    const answerArray = [
        [0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 2, 2, 0, 1, 0, 4, 0],
        [0, 0, 0, 0, 0, 3, 0, 1, 0, 0],
        [1, 2, 0, 1, 0, 0, 1, 1, 0, 1],
        [0, 2, 0, 1, 0, 0, 0, 1, 0, 0],
        [1, 0, 3, 1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 1, 0, 0, 0, 0, 1, 1],
        [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
        [0, 4, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 1, 0, 0, 0]
    ];

    // --- Generate empty table for user input
    const tbody = document.querySelector("#quiz-table tbody");
    answerArray.forEach((row, i) => {
        const tr = document.createElement("tr");
        const rowHeader = document.createElement("th");
        rowHeader.textContent = i + 1;
        tr.appendChild(rowHeader);

        row.forEach((_, j) => {
            const td = document.createElement("td");
            const input = document.createElement("input");
            input.type = "number";
            input.min = 0;
            input.dataset.row = i;
            input.dataset.col = j;
            td.appendChild(input);
            tr.appendChild(td);
        });

        tbody.appendChild(tr);
    });

    // --- Check user's answers
    function checkAnswers() {
        let allCorrect = true;
        document.querySelectorAll("#quiz-table input").forEach(input => {
            const row = input.dataset.row;
            const col = input.dataset.col;
            const userVal = parseInt(input.value) || 0;
            if (userVal !== answerArray[row][col]) {
                allCorrect = false;
                input.style.backgroundColor = "#f99"; // wrong
            } else {
                input.style.backgroundColor = "#9f9"; // correct
            }
        });

        if (allCorrect) {
            const imageUrl = document.getElementById("image-url").value.trim();
            if (imageUrl) {
                document.getElementById("unlock-image").src = imageUrl;
            } else {
                document.getElementById("unlock-image").src = "https://via.placeholder.com/600x300.png?text=You+Unlocked+It!";
            }
            document.getElementById("unlock-image").style.display = "block";
            alert("🎉 Correct! You've unlocked the image!");
        } else {
            alert("Some answers are incorrect. Keep trying!");
        }
    }
</script>

</body>
</html>
